import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(
  readFileSync(join(root, "design/tokens.json"), "utf8"),
);
const header =
  "/* GENERATED by scripts/build-tokens.mjs from design/tokens.json — do not edit */\n\n";
const vars = (values, prefix = "color") =>
  Object.entries(values)
    .map(
      ([name, value]) => `  --${prefix ? `${prefix}-` : ""}${name}: ${value};`,
    )
    .join("\n");

function baseVars(theme) {
  return [
    vars(tokens.color[theme]),
    vars(tokens.font, "font"),
    vars(tokens.radius, "radius"),
    vars(tokens.size, ""),
    vars(tokens.motion, "motion"),
  ].join("\n");
}

const aliases = `  --color-primary: var(--color-ink);\n  --color-text: var(--color-ink);\n  --color-secondary: var(--color-ink-muted);\n  --color-edge: var(--color-rule);\n  --color-background: var(--color-ground);\n  --color-background-ui: var(--color-surface);\n  --color-surface-raised: var(--color-surface);\n  --color-accent-hot: var(--color-accent-hover);\n  --color-ok: var(--color-ink);\n  --color-info: var(--color-accent);\n  --color-mid-gray: var(--color-ink-muted);\n  --color-logo-primary: var(--color-accent);\n  --color-logo-stroke: var(--color-ink);\n  --color-text-stroke: var(--color-ink);\n  --color-accent-glow: transparent;\n  --color-accent-glow-soft: transparent;\n  --font-display: var(--font-serif);\n  --font-data: var(--font-mono);\n  --ease-spring: ease-out;`;

const main = `${header}@theme {\n${baseVars("day")}\n${aliases}\n}\n\n[data-theme="evening"] {\n${vars(tokens.color.evening)}\n}\n\n@media (prefers-reduced-motion: reduce) {\n  :root {\n    --motion-fast: 0ms;\n  }\n}\n`;
const webview = (theme) =>
  `${header}:root {\n${baseVars(theme)}\n}\n\n[data-theme="evening"] {\n${vars(tokens.color.evening)}\n}\n`;

const outputs = new Map([
  ["src/theme/tokens.css", main],
  ["src/meeting/tokens.css", webview("day")],
  ["src/overlay/tokens.css", webview("day")],
]);
const check = process.argv.includes("--check");
let different = false;
for (const [relative, content] of outputs) {
  const path = join(root, relative);
  if (check) {
    if (!existsSync(path) || readFileSync(path, "utf8") !== content) {
      console.error(relative);
      different = true;
    }
  } else {
    writeFileSync(path, content, "utf8");
  }
}
if (check && different) process.exitCode = 1;
